### ISSUE TITLE
Update to latest anchor.js version?

### ISSUE THREAD

**Issue by phillchill** [getgrav/grav-plugin-anchors#4]
I just noticed the anchor.js version in this repo is 1.2.1, while the original anchor.js project has reached version 3.2.2
https://github.com/bryanbraun/anchorjs/releases

time for an update?

**Comment by flaviocopes** [comment]
Sure, submit a PR and we'll gladly merge it.

**Comment by Sogl** [comment]
@phillchill @flaviocopes Done :wink: 
https://github.com/getgrav/grav-plugin-anchors/pull/6

**Comment by rhukster** [comment]
Thanks for the PR @Sogl !
