### ISSUE TITLE
anchor icon doubled

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav-plugin-anchors#7]
Installed anchor plugin, result:
![anchor](https://cloud.githubusercontent.com/assets/12480617/23768987/1db637da-050e-11e7-805e-c87b96829e25.png)

**Comment by rhukster** [comment]
The current released version on the GitHub version?

**Comment by axel-rank** [comment]
Installed in admin panel, latest release.
![anchors](https://cloud.githubusercontent.com/assets/12480617/23786301/6d64150a-056c-11e7-8dd4-b5f8c81eb841.png)

**Comment by axel-rank** [comment]
works if anchors placement is left:

![anchors](https://cloud.githubusercontent.com/assets/12480617/24629353/03de88e4-18b9-11e7-8bf1-c5b0a86be0a8.png)

**Comment by flaviocopes** [comment]
Might be a theme issue, as I cannot replicate it. Is the site publicly accessible?

**Comment by axel-rank** [comment]
Yes,
www.axelrank.de

**Comment by axel-rank** [comment]
yes, something with my theme inheritance. tested clean agency theme and it's working so must be on my side I guess.
